USE [hansung]
GO

SELECT [id]
      ,[code]
      ,[salesemployee]
      ,[zonecode]
      ,[name]
      ,[registrationnumber]
      ,[representative]
      ,[phonenumber]
      ,[fax]
      ,[mobilephone]
      ,[email]
      ,[headofficeaddress]
      ,[destinationphone]
      ,[destinationaddress]
      ,[transactionbalance]
      ,[creditlimit]
      ,[transactionaccountnumber]
      ,[datecreate]
      ,[lastupdate]
      ,[usercreate]
      ,[userupdate]
      ,[isdelete]
      ,[idcode]
      ,[icondola]
      ,[iconwon]
  FROM [dbo].[customer]
GO

