//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hansung.datamoder
{
    using System;
    using System.Collections.Generic;
    
    public partial class billbuy
    {
        public long id { get; set; }
        public Nullable<System.DateTime> orderdate { get; set; }
        public Nullable<int> tradingmission { get; set; }
        public string terms { get; set; }
        public Nullable<System.DateTime> contractdate { get; set; }
        public Nullable<int> orderingemployer { get; set; }
        public Nullable<int> customer { get; set; }
        public Nullable<int> warehouse { get; set; }
        public Nullable<double> paymoney { get; set; }
        public string ordernumber { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> dateconfirmation { get; set; }
        public Nullable<System.DateTime> datecreate { get; set; }
        public Nullable<System.DateTime> lastupdate { get; set; }
        public Nullable<int> usercreate { get; set; }
        public Nullable<int> userupdate { get; set; }
        public string namewarehouse { get; set; }
        public string codeid { get; set; }
        public string phone { get; set; }
        public string notebill { get; set; }
        public string currency { get; set; }
        public string paymentoption { get; set; }
        public string note { get; set; }
        public Nullable<double> money { get; set; }
        public Nullable<double> tolerancepercent { get; set; }
        public Nullable<double> tolerancemoney { get; set; }
        public Nullable<double> usance { get; set; }
        public Nullable<System.DateTime> datebeginpayment { get; set; }
        public Nullable<System.DateTime> creditduedate { get; set; }
        public string orderbill { get; set; }
        public string history { get; set; }
    }
}
