//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hansung.datamoder
{
    using System;
    using System.Collections.Generic;
    
    public partial class carship
    {
        public long id { get; set; }
        public string codebill { get; set; }
        public string codeid { get; set; }
        public Nullable<int> company { get; set; }
        public string numberofvehicles { get; set; }
        public Nullable<double> rate { get; set; }
        public Nullable<System.DateTime> verifyingacceptance { get; set; }
        public Nullable<int> deliveryworker { get; set; }
        public Nullable<System.DateTime> shippingtime { get; set; }
        public Nullable<System.DateTime> datecreate { get; set; }
        public Nullable<System.DateTime> lastupdate { get; set; }
        public Nullable<int> usercreate { get; set; }
        public Nullable<int> userupdate { get; set; }
        public string forwardingnumber { get; set; }
        public string numbill { get; set; }
        public Nullable<double> qltBox { get; set; }
        public string ship { get; set; }
        public string indexbox { get; set; }
        public string agree { get; set; }
        public string history { get; set; }
    }
}
