//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hansung.datamoder
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public int id { get; set; }
        public string code { get; set; }
        public Nullable<int> salesemployee { get; set; }
        public string zonecode { get; set; }
        public string name { get; set; }
        public string registrationnumber { get; set; }
        public string representative { get; set; }
        public string phonenumber { get; set; }
        public string fax { get; set; }
        public string mobilephone { get; set; }
        public string email { get; set; }
        public string headofficeaddress { get; set; }
        public string destinationphone { get; set; }
        public string destinationaddress { get; set; }
        public Nullable<double> transactionbalance { get; set; }
        public Nullable<double> creditlimit { get; set; }
        public string transactionaccountnumber { get; set; }
        public Nullable<System.DateTime> datecreate { get; set; }
        public Nullable<System.DateTime> lastupdate { get; set; }
        public Nullable<int> usercreate { get; set; }
        public Nullable<int> userupdate { get; set; }
        public Nullable<bool> isdelete { get; set; }
        public Nullable<int> idcode { get; set; }
        public string icondola { get; set; }
        public string iconwon { get; set; }
    }
}
