//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hansung.datamoder
{
    using System;
    using System.Collections.Generic;
    
    public partial class detailship
    {
        public long id { get; set; }
        public string codebill { get; set; }
        public string codeid { get; set; }
        public string orderbill { get; set; }
        public string numbership { get; set; }
        public Nullable<System.DateTime> duedate { get; set; }
        public Nullable<System.DateTime> departuredate { get; set; }
        public Nullable<System.DateTime> dateofarrival { get; set; }
        public Nullable<System.DateTime> conDuedate { get; set; }
        public string shipname { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> datecreate { get; set; }
        public Nullable<System.DateTime> lastupdate { get; set; }
        public Nullable<int> usercreate { get; set; }
        public Nullable<int> userupdate { get; set; }
        public string nameshipname { get; set; }
        public Nullable<double> qltbox { get; set; }
        public Nullable<System.DateTime> dateclearance { get; set; }
        public Nullable<System.DateTime> customsday { get; set; }
        public string port { get; set; }
        public string containernumber { get; set; }
        public Nullable<System.DateTime> daycertificate { get; set; }
        public string sizefit { get; set; }
        public Nullable<System.DateTime> containerday { get; set; }
        public Nullable<System.DateTime> conreturnday { get; set; }
        public Nullable<System.DateTime> requestday { get; set; }
        public Nullable<System.DateTime> confirmreceiptday { get; set; }
        public string serinumber { get; set; }
        public string prodcode { get; set; }
        public string casenom { get; set; }
        public Nullable<System.DateTime> proddate { get; set; }
        public string shipnum { get; set; }
        public string indexbox { get; set; }
    }
}
