//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hansung.datamoder
{
    using System;
    using System.Collections.Generic;
    
    public partial class detailwarehouse
    {
        public int id { get; set; }
        public string name { get; set; }
        public string destination { get; set; }
        public string rowdestination { get; set; }
        public string YajiSelection { get; set; }
        public string rowYaji { get; set; }
        public string container { get; set; }
    }
}
