//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hansung.datamoder
{
    using System;
    using System.Collections.Generic;
    
    public partial class detail_car
    {
        public long id { get; set; }
        public string ship { get; set; }
        public string codeitem { get; set; }
        public Nullable<double> qltbox { get; set; }
        public Nullable<System.DateTime> datecreate { get; set; }
        public Nullable<System.DateTime> lastupdate { get; set; }
        public Nullable<int> usercreate { get; set; }
        public Nullable<int> userupdate { get; set; }
        public string codecar { get; set; }
        public string codebill { get; set; }
        public string history { get; set; }
        public Nullable<int> iditem { get; set; }
        public Nullable<double> box { get; set; }
    }
}
