//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hansung.datamoder
{
    using System;
    using System.Collections.Generic;
    
    public partial class detailbillbuy
    {
        public long id { get; set; }
        public Nullable<int> iditem { get; set; }
        public string nameitem { get; set; }
        public string standard { get; set; }
        public Nullable<double> quantityincase { get; set; }
        public Nullable<double> qltcase { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> pricesupply { get; set; }
        public Nullable<double> vat { get; set; }
        public Nullable<double> totalamount { get; set; }
        public Nullable<int> qltcontainer { get; set; }
        public Nullable<double> sqm { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> datecreate { get; set; }
        public Nullable<System.DateTime> lastupdate { get; set; }
        public Nullable<int> usercreate { get; set; }
        public Nullable<int> userupdate { get; set; }
        public string codeitem { get; set; }
        public string codebill { get; set; }
        public string codeid { get; set; }
        public string codeship { get; set; }
    }
}
