//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hansung.datamoder
{
    using System;
    using System.Collections.Generic;
    
    public partial class historybillsale
    {
        public long id { get; set; }
        public Nullable<int> idold { get; set; }
        public string contenold { get; set; }
        public string contennew { get; set; }
        public Nullable<System.DateTime> datecreate { get; set; }
        public Nullable<System.DateTime> lastupdate { get; set; }
        public Nullable<int> usercreate { get; set; }
        public Nullable<int> userupdate { get; set; }
        public string actions { get; set; }
        public string codeid { get; set; }
        public string subcode { get; set; }
        public string inforbill { get; set; }
    }
}
