//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hansung.datamoder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inputwarehouse
    {
        public long id { get; set; }
        public string seriesnum { get; set; }
        public string destination { get; set; }
        public string rowdestination { get; set; }
        public string YajiSelection { get; set; }
        public string rowYaji { get; set; }
        public string container { get; set; }
        public Nullable<int> itemid { get; set; }
        public string itemcode { get; set; }
        public string itemname { get; set; }
        public string size { get; set; }
        public Nullable<double> qltincase { get; set; }
        public Nullable<double> qltbox { get; set; }
        public string problems { get; set; }
        public string defecttype { get; set; }
        public string manufacturer { get; set; }
        public string remarksitem { get; set; }
        public string location { get; set; }
        public string purchasenotes { get; set; }
        public string attachments { get; set; }
        public Nullable<System.DateTime> datecreate { get; set; }
        public Nullable<System.DateTime> lastupdate { get; set; }
        public Nullable<int> usercreate { get; set; }
        public Nullable<int> userupdate { get; set; }
        public string inspnumber { get; set; }
    }
}
