//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hansung.datamoder
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemList
    {
        public int id { get; set; }
        public string itemcode { get; set; }
        public string itemduzoncode { get; set; }
        public string itemname { get; set; }
        public Nullable<double> quantityincase { get; set; }
        public Nullable<double> specifiedarea { get; set; }
        public Nullable<double> safetystockquantity { get; set; }
        public string manufacturer { get; set; }
        public string status { get; set; }
        public string itembrief { get; set; }
        public Nullable<System.DateTime> datecreate { get; set; }
        public Nullable<System.DateTime> lastupdate { get; set; }
        public Nullable<int> usercreate { get; set; }
        public Nullable<int> userupdate { get; set; }
        public string standard { get; set; }
        public Nullable<bool> isdelete { get; set; }
        public Nullable<double> width { get; set; }
        public Nullable<double> unitprice1 { get; set; }
        public Nullable<double> unitprice2 { get; set; }
        public Nullable<double> unitprice3 { get; set; }
        public Nullable<double> height { get; set; }
    }
}
