//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hansung.datamoder
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuActionPermission
    {
        public int EmpId { get; set; }
        public int MenuId { get; set; }
        public bool IsAllowRetrieve { get; set; }
        public bool IsAllowCreate { get; set; }
        public bool IsAllowUpdate { get; set; }
        public bool IsAllowDelete { get; set; }
        public bool IsAllowUpload { get; set; }
        public bool IsAllowPrint { get; set; }
        public bool IsAllowExport { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    }
}
