//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hansung.datamoder
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hansungEntities : DbContext
    {
        public hansungEntities()
            : base("name=hansungEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<billbuy> billbuys { get; set; }
        public virtual DbSet<carship> carships { get; set; }
        public virtual DbSet<changewarehouse> changewarehouses { get; set; }
        public virtual DbSet<container_location> container_location { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<department> departments { get; set; }
        public virtual DbSet<detail_car> detail_car { get; set; }
        public virtual DbSet<detailbillbuy> detailbillbuys { get; set; }
        public virtual DbSet<detailchangewarehouse> detailchangewarehouses { get; set; }
        public virtual DbSet<detailorder> detailorders { get; set; }
        public virtual DbSet<detailship> detailships { get; set; }
        public virtual DbSet<detailwarehouse> detailwarehouses { get; set; }
        public virtual DbSet<historybillsale> historybillsales { get; set; }
        public virtual DbSet<Inputwarehouse> Inputwarehouses { get; set; }
        public virtual DbSet<inspection> inspections { get; set; }
        public virtual DbSet<ItemList> ItemLists { get; set; }
        public virtual DbSet<jigo_location> jigo_location { get; set; }
        public virtual DbSet<orderslip> orderslips { get; set; }
        public virtual DbSet<payment> payments { get; set; }
        public virtual DbSet<paymentOrder> paymentOrders { get; set; }
        public virtual DbSet<plan> plans { get; set; }
        public virtual DbSet<position> positions { get; set; }
        public virtual DbSet<rawyaji_location> rawyaji_location { get; set; }
        public virtual DbSet<rowjigo_location> rowjigo_location { get; set; }
        public virtual DbSet<serinumber> serinumbers { get; set; }
        public virtual DbSet<ship> ships { get; set; }
        public virtual DbSet<styleItem> styleItems { get; set; }
        public virtual DbSet<subship> subships { get; set; }
        public virtual DbSet<table_detail_erorr> table_detail_erorr { get; set; }
        public virtual DbSet<Table_Erorr> Table_Erorr { get; set; }
        public virtual DbSet<Table_qlt_erorr> Table_qlt_erorr { get; set; }
        public virtual DbSet<tradingmission> tradingmissions { get; set; }
        public virtual DbSet<warehouse> warehouses { get; set; }
        public virtual DbSet<warehouse_location> warehouse_location { get; set; }
        public virtual DbSet<yaji_location> yaji_location { get; set; }
        public virtual DbSet<ObjectPropertyPermission> ObjectPropertyPermissions { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<MenuGroup> MenuGroups { get; set; }
        public virtual DbSet<MenuActionPermission> MenuActionPermissions { get; set; }
    }
}
