//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hansung.datamoder
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderslip
    {
        public long id { get; set; }
        public string orderdate { get; set; }
        public Nullable<int> salesrepresentative { get; set; }
        public Nullable<int> customercompany { get; set; }
        public string customercontacts { get; set; }
        public string terms { get; set; }
        public Nullable<bool> receivables { get; set; }
        public Nullable<int> warehouse { get; set; }
        public Nullable<System.DateTime> issuedate { get; set; }
        public string contactphone { get; set; }
        public string frame { get; set; }
        public string destinationaddress { get; set; }
        public string remarks { get; set; }
        public Nullable<System.DateTime> datecreate { get; set; }
        public Nullable<System.DateTime> lastupdate { get; set; }
        public Nullable<int> usercreate { get; set; }
        public Nullable<int> userupdate { get; set; }
        public string codeid { get; set; }
        public Nullable<double> transactionbalancectm { get; set; }
        public Nullable<System.DateTime> orderdatetime { get; set; }
        public string history { get; set; }
    }
}
