//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hansung.datamoder
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        public long id { get; set; }
        public string codeorder { get; set; }
        public Nullable<System.DateTime> paymentdate { get; set; }
        public Nullable<int> employer { get; set; }
        public Nullable<int> customer { get; set; }
        public string transactionterms { get; set; }
        public Nullable<double> cashT_T { get; set; }
        public Nullable<double> billL_C { get; set; }
        public string paymentaccount { get; set; }
        public Nullable<double> feesmoney { get; set; }
        public string remark { get; set; }
        public string codebill { get; set; }
        public string codeid { get; set; }
        public Nullable<System.DateTime> datecreate { get; set; }
        public Nullable<System.DateTime> lastupdate { get; set; }
        public Nullable<int> usercreate { get; set; }
        public Nullable<int> userupdate { get; set; }
        public string employerstr { get; set; }
    }
}
