//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hansung.datamoder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Erorr
    {
        public int id { get; set; }
        public string numbercode { get; set; }
        public Nullable<int> poor_handling_charge { get; set; }
        public Nullable<int> warehouse_id { get; set; }
        public string defective_processing_type { get; set; }
        public Nullable<System.DateTime> approved { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> datecreate { get; set; }
        public Nullable<System.DateTime> lastupdate { get; set; }
        public Nullable<int> usercreate { get; set; }
        public Nullable<int> userupdate { get; set; }
        public string codeid { get; set; }
    }
}
